// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package tracing

import "unsafe"
import "syscall"

var _ unsafe.Pointer

var (
	modsechost = syscall.NewLazyDLL("sechost.dll")

	procOpenTrace = modsechost.NewProc("OpenTrace")
)

func _OpenTrace(logfile *EventTraceLogfile) (h syscall.Handle) {
	r0, _, _ := syscall.Syscall(procOpenTrace.Addr(), 1, uintptr(unsafe.Pointer(logfile)), 0, 0)
	h = syscall.Handle(r0)
	return
}
